### ISSUE TITLE
Create game quiz anime image from my api

### ISSUE THREAD

**Issue by Piyoxz** [InosID/inos-baileys-wabot#23]
Quiz game

**Comment by Piyoxz** [comment]
https://piyo-api.herokuapp.com/

**Comment by moo-d** [comment]
Uh...

**Comment by moo-d** [comment]
Are you in the whatsapp group?

**Comment by Piyoxz** [comment]
nope, I see your code doesn't use api , everything is scrape

**Comment by Piyoxz** [comment]
> Oh, yes. This is a full scrape whatsapp bot. But it's up to you, want to use API or scrape.

send money to me if you want the scrape code xixixi

**Comment by Piyoxz** [comment]
hahaha just kidding

**Comment by Piyoxz** [comment]
use the API first, maybe later this afternoon I will push it to this github

**Comment by Piyoxz** [comment]
bro
